# Generated by Django 4.2 on 2024-03-22 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_time_birth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default=None, max_length=1)),
                ('place_birth', models.CharField(max_length=50)),
                ('mothersName', models.CharField(max_length=50)),
                ('fathersName', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('did', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_time_death', models.DateTimeField()),
                ('place_death', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=150)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.birthcertificate')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('hospitalID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPractitioner',
            fields=[
                ('medicalID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default=None, max_length=1)),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('General Physician', 'General Physician'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Gynecologist', 'Gynecologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Nephrologist', 'Nephrologist'), ('Dentist', 'Dentist'), ('Nurse', 'Nurse')], default=None, max_length=50)),
                ('hospitalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('type_med', models.CharField(choices=[('antipyretic', 'antipyretic'), ('analgesic', 'aanalgesic'), ('antihistamine', 'antihistamine'), ('antibiotic', 'antibiotic'), ('antidepressant', 'antidepressant'), ('anticoagulant', 'anticoagulant'), ('antihypertensive', 'antihypertensive'), ('anti-inflammatory', 'anti-inflammatory'), ('antiviral', 'antiviral'), ('diuretic', 'diuretic')], default=None, max_length=50)),
                ('regulatoryClass', models.CharField(choices=[('general', 'general'), ('restricted', 'restricted')], default=None, max_length=50)),
                ('medCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('aadharNo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default=None, max_length=1)),
                ('date_birth', models.DateField()),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default=None, max_length=3)),
                ('emergencyContact', models.CharField(max_length=10)),
                ('criticalInfo', models.CharField(max_length=150)),
                ('bid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.birthcertificate')),
                ('did', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.deathcertificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pulse', models.IntegerField()),
                ('bp_High', models.IntegerField()),
                ('bp_low', models.IntegerField()),
                ('spO2', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bsa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucose', models.IntegerField()),
                ('abnormalities', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('aadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.patient')),
                ('hospitalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('tid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('disease', models.CharField(max_length=75)),
                ('severity', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('admitted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], default='Not Required', max_length=20)),
                ('treatmentCost', models.IntegerField()),
                ('aadharNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.patient')),
                ('hospitalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.hospital')),
                ('medicalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.medicalpractitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medicines', to='treatment.medicine')),
                ('tid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medicines', to='treatment.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='hospitalID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.hospital'),
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='hospitalID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.hospital'),
        ),
    ]
