# Generated by Django 4.2 on 2024-03-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_birth',
            new_name='date_of_birth',
        ),
    ]
