# Generated by Django 4.2 on 2024-03-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_hospital_status_delete_hospitalregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hospital')),
            ],
        ),
    ]
