# Generated by Django 4.2 on 2024-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_alter_hospital_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalRegistrationRequest',
        ),
    ]
