# Generated by Django 4.2 on 2024-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_delete_hospitalregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='query',
            field=models.CharField(choices=[('Wrong Treatment', 'Wrong Treatment'), ('False Treatment', 'False Treatment'), ('OK', 'OK')], default='OK', max_length=20),
        ),
    ]
