# Generated by Django 4.2 on 2024-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0011_alter_treatment_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
