# Generated by Django 4.2 on 2024-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0012_alter_treatment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='suggestions',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='query',
            field=models.CharField(choices=[('Wrong Treatment', 'Wrong Treatment'), ('False Treatment', 'False Treatment'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
