# Generated by Django 4.2 on 2024-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0014_treatment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='query',
            field=models.CharField(choices=[('Wrong Treatment', 'Wrong Treatment'), ('False Treatment', 'False Treatment'), ('No', 'No'), ('Addressed', 'Addressed')], default='No', max_length=20),
        ),
    ]
