# Generated by Django 4.2 on 2024-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0017_treatment_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='criticalInfo',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
