# Generated by Django 4.2 on 2024-03-31 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0018_alter_patient_criticalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='Unnamed City', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Unnamed State', max_length=15),
            preserve_default=False,
        ),
    ]
