# Generated by Django 4.2 on 2024-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0019_remove_hospital_name_hospital_city_hospital_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathcertificate',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='hospitalID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='did',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='severity',
        ),
        migrations.AddField(
            model_name='treatment',
            name='advisedTest',
            field=models.CharField(default='no tests', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='symptoms',
            field=models.CharField(default='no symp', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type_med',
            field=models.CharField(choices=[('Antipyretic', 'Antipyretic'), ('Analgesic', 'Analgesic'), ('Antihistamine', 'Antihistamine'), ('Antibiotic', 'Antibiotic'), ('Antidepressant', 'Antidepressant'), ('Anticoagulant', 'Anticoagulant'), ('Antihypertensive', 'Antihypertensive'), ('Anti-inflammatory', 'Anti-inflammatory'), ('Antiviral', 'Antiviral'), ('Diuretic', 'Diuretic'), ('Antifungal', 'Antifungal'), ('Antiemetic', 'Antiemetic'), ('Anticonvulsant', 'Anticonvulsant'), ('Bronchodilator', 'Bronchodilator'), ('Muscle Relaxant', 'Muscle Relaxant'), ('Laxative', 'Laxative'), ('Antacid', 'Antacid'), ('Hormone Replacement Therapy (HRT)', 'Hormone Replacement Therapy (HRT)'), ('Immunosuppressant', 'Immunosuppressant'), ('Antimigraine', 'Antimigraine'), ('Antidiabetic', 'Antidiabetic')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergencyContact',
            field=models.CharField(max_length=11),
        ),
        migrations.DeleteModel(
            name='BirthCertificate',
        ),
        migrations.DeleteModel(
            name='DeathCertificate',
        ),
    ]
