# Generated by Django 4.2 on 2024-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0020_remove_deathcertificate_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpractitioner',
            name='status',
            field=models.CharField(choices=[('Authorized', 'Authorized'), ('Suspended', 'Suspended')], default='Authorized', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
