# Generated by Django 4.2 on 2024-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0021_medicalpractitioner_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='status',
            field=models.CharField(choices=[('Authorized', 'Authorized'), ('Suspended', 'Suspended'), ('Permanently Suspended', 'Permanently Suspended')], default='Authorized', max_length=21),
        ),
    ]
