# Generated by Django 4.2 on 2024-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0022_alter_medicalpractitioner_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="advisedTest",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
